Harden: Add GNU `awk` check to `rg` wrapper
- Also, Improve: UX: Print more helpful how-to-install
  `rg` message.

diff --git a/bin/vim-grepprg-rg-sort b/bin/vim-grepprg-rg-sort
--- a/bin/vim-grepprg-rg-sort
+++ b/bin/vim-grepprg-rg-sort
@@ -50,23 +50,48 @@ DUBS_VIM_RG_MAX_COLS=200
 #
 #               rg ... | sort --debug -t: -k1,1 -k2,2n
 
+check_deps () {
+  must_verify_rip_grep
+  must_verify_gnu_awk
+}
+
+# SAVVY: Verify gawk, not mawk.
+# - On stock Debian 12, before gawk installed:
+#     /bin/awk -> /etc/alternatives/awk
+#   and
+#     /etc/alternatives/awk -> /usr/bin/mawk
+must_verify_gnu_awk () {
+  if awk --version 2>/dev/null | head -n 1 | grep -q -e "^GNU Awk"; then
+
+    return 0
+  fi
+
+  >&2 echo "ERROR: Cound not find dependency: GNU Awk"
+  >&2 echo "- HINT: Try, e.g., \`apt install gawk\`"
+
+  exit 1
+}
+
+must_verify_rip_grep () {
+  if rip_grep_executable > /dev/null; then
+
+    return 0
+  fi
+
+  >&2 echo "ERROR: Cound not find dependency: RipGrep"
+  >&2 echo "- HINT: Try, e.g., \`apt install rg\`"
+
+  exit 1
+}
+
 # Resolve path to `rg`, so that we don't inadvertently call user's `rg`
 # alias (e.g., user aliases `rg` to `tag`, for interactive CLI results).
+# - CALSO: Using `command rg` would similarly achieve the same result.
 rip_grep_executable () {
   type -P rg
 }
 
-must_verify_rip_grep () {
-  rip_grep_executable > /dev/null \
-    && return
-
-  echo "\
-ERROR: Cound not find RipGrep!
-- CXREF: Check rip_grep_executable:
-    $0"
-
-  exit 1
-}
+# ***
 
 expand_paths () {
   awk -F: '
@@ -156,7 +181,7 @@ rip_grep_sleep_repeat () {
 }
 
 main () {
-  must_verify_rip_grep
+  check_deps
 
   rip_grep_sleep_repeat "$@"
 }
